language: node_js
node_js:
- '8'
before_install:
 - npm i npm-cli-login -g
 - npm-cli-login -u "${NPM_USER}" -p "${NPM_PASSWORD}" -e "${NPM_EMAIL}"
 - npm who
install:
- npm install jsdoc -g
- npm install
script:
- ./ci/build.js
- ./ci/shim.js
- ./ci/test.js
after_success:
- ./ci/travis/publish.js
env:
  secure: "m912kUh5rvZg5JeUVNreqblCydlZWzrPYVEMCWqD4bpGFBDzU98oE7Ly8+10/Pyc8JEmW9oRWjiW4u4PW/Wf8/h0gYgyucfQh1D8/Q7GJicqcE8KGqPZsW30FC3au/B83P05oZ8bPhte/9YxVRnzdatEdm1mARlN8foWFLoeijR2Tt4m5h7aEa3HjIOe8gqHGkX4lk1FRG1FPQX7vXqaGSMnEd1cbfllCdLFSH1JeWwp8g1OyzYWWe8zxVnDZp5A55AGMzogGlEtIXqf+RUgqVULfwTHihNUVttMeiWnD+nUygfJmQXUNn/efq2rEFOqwWAYB/cObnwjFGb1wVVzVxISOLo2C8ha7IasryrU8ODWCRrYot68t+Si2rVHN7fxGTTCXi3pCLJY5hflguooing+VMHXMQ3PnWfRNlRUufL8OkMNDQSMqRYzVSUHK5D32hjYMApcFG2XxjNy8Pn81b2hu43x8dsqJIqhsQBz0HUUu4b62c2xixaXpjLseA/SAACdVOVRGgcE+cQsw2cmbUS49O2VyAbaHkvNyYKPlWcUpFi1sHsy6maYSoJoT5eNBOWDz4Ia7zfpQaf6AWevluhe0SinmSxTORmwhYZF0XoatCvxHoXnIAQBAS062V/CT1dFqV6ipO+s7E4Ws/CyVEZWJAn46QE0+En+yaZ36TU="
env:
  secure: "G5kZMu9MsJqokMm3EqrSlDZ14Ampm4zgz3Q4jWHBtZWBx6ayS67Yo/YlhxU2kX1FGUv4FQADv2x5v/q+ujjlraOaeVt+jdzjBo3/aGPRpk+Ymr8Zj01hR7F4/DJo3GFbzkFzqphf4twhFEsocZtGY52O6GBhFgZoqmu+13RmwC8+F8kgIMZaBlfVjqwLXXnsnALBHI5jzWwWLhAaTTdzYN47BjL3NRtoKhQM8DZxS3jIHV04/4KvK6GhOSnUiSyMD2AnDh6fcW4BVFN6HQM6M3bIn0oYkOvBMKVzjnG2ibXHqpgl0QbFAiPoj/tu8hq3LEYD3EeejCeLpEezdA7pev3wwSc6qIRQ5CZOL/+rgubz+SYIuZ68TAHJ/ntZRvQl+zKH5Kv/31vPzokMe6HVJJfuDgqN/s32HSQWKQ5dpGS2DJqlWAB7ahknTlnxeM0e3NUx5IXe03fgCu/FjFZ+71VVYWKgXoTUlCtgR+CYeBiqh4fLkUzm278uGClRco3jF5bN1cAFT8kTqjOLf3ya1cV8oOcazNb7lYO24HniBrom1X3yYXgNO5fA6WWF/6a4vW142lz3/aCeQ2iym6Af/Jfs9Qgt34lOFcJ/eNi1pq9lweKiLOtvWMHvXRuwzO/x6vC2Rb+HvSRxoxL0Mbbo+z0W1VsSyS4RoJavALXU+3I="
